development:
  adapter: postgresql
  encoding: unicode
  database: abiteapp_development
  pool: 5
  username: postgres
  password: postgres
  host: 192.168.1.133

production:
  adapter: postgresql
  encoding: unicode
  database: abiteapp_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: abiteapp_test
  pool: 5
  username: postgres
  password: postgres